/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking_hotel;

import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author cchan
 */
public class For_book extends javax.swing.JFrame {

    private String selectedRoom;

    /**
     * Creates new form For_book
     */
    public For_book() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("For Book");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();
        cbmx_room = new javax.swing.JComboBox<>();
        btn_Submit = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking ");

        btn_Cancel.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        cbmx_room.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbmx_room.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room", "101", "102", "103", "104", "105" }));
        cbmx_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmx_roomActionPerformed(evt);
            }
        });

        btn_Submit.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        btn_Submit.setText("Submit");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setText("Name");

        jLabel3.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btn_Cancel)
                        .addGap(167, 167, 167)
                        .addComponent(btn_Submit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbmx_room, 0, 287, Short.MAX_VALUE)
                            .addComponent(txt_name)
                            .addComponent(txt_phone))))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(cbmx_room, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        selectedRoom = (String) cbmx_room.getSelectedItem();
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        String selectedRoom = (String) cbmx_room.getSelectedItem();
        String Name = txt_name.getText();
        String Phone = txt_phone.getText();
        String RoomType = getRoomType(selectedRoom);
        String Price = getPrice(selectedRoom);
        selectedRoom = (String) cbmx_room.getSelectedItem();

        try {
            FileWriter Writer = new FileWriter("src/Booking_Hotel/Booking_Person.txt", true);
            Writer.write(selectedRoom + "," + RoomType + "," + Price + "," + Name + "," + Phone);
            Writer.close();
            JOptionPane.showMessageDialog(this, "Room Type: " + getRoomType(selectedRoom));
            JOptionPane.showMessageDialog(this, "Booking successful. >w<");

            cbmx_room.removeItem(selectedRoom);

            Manage_Room manageRoom = new Manage_Room();
            manageRoom.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error. ", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_SubmitActionPerformed

    public String getSelectedRoom() {
        return selectedRoom;
    }

    public void setSelectedRoom(String room) {
        selectedRoom = room;
        cbmx_room.setSelectedItem(room);
    }

    private String getRoomType(String selectedRoom) {
        switch (selectedRoom) {
            case "101":
                return "Standard";
            case "102":
                return "Deluxe";
            case "103":
                return "Premium";
            case "104":
                return "Superior";
            case "105":
                return "Super Earth";
            default:
                return " ";
        }
    }

    private String getPrice(String selectedRoom) {
        switch (selectedRoom) {
            case "101":
                return "3000";
            case "102":
                return "4500";
            case "103":
                return "6000";
            case "104":
                return "7500";
            case "105":
                return "9500";
            default:
                return " ";
        }
    }
    private void cbmx_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmx_roomActionPerformed
        // TODO add your handling code here:

        String selectedRoom = (String) cbmx_room.getSelectedItem();
        String roomType = " ";
        switch (selectedRoom) {
            case "101":
                roomType = "Standard 3000 ฿";
                break;
            case "102":
                roomType = "Deluxe 4000 ฿";
                break;
            case "103":
                roomType = "Premium 6500 ฿";
                break;
            case "104":
                roomType = "Superior 7500 ฿";
                break;
            case "105":
                roomType = "Super Earth 9500 ฿";
                break;
            default:
                roomType = " ";
                break;
        }


    }//GEN-LAST:event_cbmx_roomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(For_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(For_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(For_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(For_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new For_book().setVisible(true);
            }

            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cbmx_room;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
