/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking_hotel;

/**
 *
 * @author LEGION
 */
public class Payment_Hotel extends javax.swing.JDialog {

    /**
     * Creates new form Payment_Hotel
     */
    public Payment_Hotel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Payment");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Payments = new javax.swing.JLabel();
        lbl_Roomnumber = new javax.swing.JLabel();
        itmbx_Roomnumber = new javax.swing.JComboBox<>();
        cbx_Roomservice = new javax.swing.JCheckBox();
        btn_calculate = new javax.swing.JButton();
        txt_Total = new javax.swing.JTextField();
        lbl_Total = new javax.swing.JLabel();
        lbl_Cash_Paid = new javax.swing.JLabel();
        txt_CashPaid = new javax.swing.JTextField();
        lbl_Change = new javax.swing.JLabel();
        txt_Change = new javax.swing.JTextField();
        btn_Pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_Payments.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        lbl_Payments.setText("Payment");

        lbl_Roomnumber.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lbl_Roomnumber.setText("Room Number");

        itmbx_Roomnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room", "Room 101", "Room 102", "Room 103", "Room 104", "Room 105" }));

        cbx_Roomservice.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        cbx_Roomservice.setText("Room Sevices");

        btn_calculate.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_calculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/accounting.png"))); // NOI18N
        btn_calculate.setText("Calculate");

        txt_Total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lbl_Total.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        lbl_Total.setText("Total");

        lbl_Cash_Paid.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        lbl_Cash_Paid.setText("Cash Paid");

        txt_CashPaid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lbl_Change.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        lbl_Change.setText("CHANGE");

        txt_Change.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btn_Pay.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_Pay.setText("PAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(lbl_Roomnumber)
                .addGap(18, 18, 18)
                .addComponent(itmbx_Roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbl_Total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Cash_Paid)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Change)
                                .addGap(26, 26, 26)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Change, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(txt_Total)
                    .addComponent(txt_CashPaid))
                .addGap(30, 30, 30)
                .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_Roomservice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Payments)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_Payments, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itmbx_Roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Roomnumber))
                .addGap(37, 37, 37)
                .addComponent(cbx_Roomservice)
                .addGap(31, 31, 31)
                .addComponent(btn_calculate)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Total)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cash_Paid)
                    .addComponent(txt_CashPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Change, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Change))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payment_Hotel dialog = new Payment_Hotel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pay;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JCheckBox cbx_Roomservice;
    private javax.swing.JComboBox<String> itmbx_Roomnumber;
    private javax.swing.JLabel lbl_Cash_Paid;
    private javax.swing.JLabel lbl_Change;
    private javax.swing.JLabel lbl_Payments;
    private javax.swing.JLabel lbl_Roomnumber;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JTextField txt_CashPaid;
    private javax.swing.JTextField txt_Change;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables
}
