/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking_hotel;

import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author LEGION
 */
public class Payment_Hotel extends javax.swing.JDialog implements Payment {

    private int roomPrice;
    private int servicePrice;

    /**
     * Creates new form Payment_Hotel
     */
    public Payment_Hotel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Payment");
    }

    @Override
    public void makePayment(int totalPrice, int cashPaid) {
    }

    private int getRoomPrice(String roomNumber) {
        int price = 0;
        try (Scanner scanner = new Scanner(new File("src/booking_hotel/Booking_Person.txt"))) {
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] bookingDetails = line.split(",");
                String currentRoomNumber = bookingDetails[0];
                if (currentRoomNumber.equals(roomNumber)) {
                    price = Integer.parseInt(bookingDetails[2]);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not found!");
        }
        return price;
    }

    private int getServicePrice(String roomNumber) {
        int price = 0;
        try (Scanner scanner = new Scanner(new File("src/booking_hotel/Booking_Person.txt"))) {
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] bookingDetails = line.split(",");
                String currentRoomNumber = bookingDetails[0];
                if (currentRoomNumber.equals(roomNumber)) {
                    price = Integer.parseInt(bookingDetails[6]);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not found!");
        }
        return price;
    }

    private void processPayment(int cashPaid, int totalPrice) {
        if (cashPaid >= totalPrice) {
            int change = cashPaid - totalPrice;
            txt_Change.setText(String.valueOf(change));
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient funds!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Payments = new javax.swing.JLabel();
        lbl_Roomnumber = new javax.swing.JLabel();
        itmbx_Roomnumber = new javax.swing.JComboBox<>();
        btn_calculate = new javax.swing.JButton();
        txt_Total = new javax.swing.JTextField();
        lbl_Total = new javax.swing.JLabel();
        lbl_Cash_Paid = new javax.swing.JLabel();
        txt_CashPaid = new javax.swing.JTextField();
        lbl_Change = new javax.swing.JLabel();
        txt_Change = new javax.swing.JTextField();
        btn_Pay = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_Payments.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        lbl_Payments.setText("Payment");

        lbl_Roomnumber.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lbl_Roomnumber.setText("Room Number");

        itmbx_Roomnumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        itmbx_Roomnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room", "Room 101", "Room 102", "Room 103", "Room 104", "Room 105" }));

        btn_calculate.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_calculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/accounting.png"))); // NOI18N
        btn_calculate.setText("Calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        txt_Total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lbl_Total.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        lbl_Total.setText("Total");

        lbl_Cash_Paid.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        lbl_Cash_Paid.setText("Cash Paid");

        txt_CashPaid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lbl_Change.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        lbl_Change.setText("CHANGE");

        txt_Change.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btn_Pay.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_Pay.setText("PAY");
        btn_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PayActionPerformed(evt);
            }
        });

        btn_Cancel.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Change)
                            .addComponent(txt_Total)
                            .addComponent(txt_CashPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Payments)
                        .addGap(189, 189, 189))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Cash_Paid)
                    .addComponent(lbl_Roomnumber)
                    .addComponent(lbl_Change)
                    .addComponent(lbl_Total))
                .addGap(18, 18, 18)
                .addComponent(itmbx_Roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_Payments, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itmbx_Roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Roomnumber))
                .addGap(43, 43, 43)
                .addComponent(btn_calculate)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Total)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cash_Paid)
                    .addComponent(txt_CashPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Change, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Change))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        // TODO add your handling code here:
        String selectedRoom = itmbx_Roomnumber.getSelectedItem().toString().replaceAll("\\D+", "");
        roomPrice = getRoomPrice(selectedRoom);
        servicePrice = getServicePrice(selectedRoom);
        int totalPrice = roomPrice + servicePrice;
        txt_Total.setText(String.valueOf(totalPrice));
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayActionPerformed
        // TODO add your handling code here:
        int cashPaid = Integer.parseInt(txt_CashPaid.getText());
        int totalPrice = Integer.parseInt(txt_Total.getText());
        processPayment(cashPaid, totalPrice);
    }//GEN-LAST:event_btn_PayActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Payment_Hotel dialog = new Payment_Hotel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Pay;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JComboBox<String> itmbx_Roomnumber;
    private javax.swing.JLabel lbl_Cash_Paid;
    private javax.swing.JLabel lbl_Change;
    private javax.swing.JLabel lbl_Payments;
    private javax.swing.JLabel lbl_Roomnumber;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JTextField txt_CashPaid;
    private javax.swing.JTextField txt_Change;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables
}
