/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking_hotel;


import javax.swing.JOptionPane;

/**
 *
 * @author LEGION
 */
public class Signup_Hotel extends javax.swing.JFrame implements Hotel_Interface {

    /**
     * Creates new form Signup_Hotel
     */
    public Signup_Hotel() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Sign-Up Admin");
    }

    @Override
    public boolean login(String username, String password) {
        return false;
    }

    @Override
    public boolean register(String username, String password) {
        return Hotel_FileHandler.writeToFile("src/booking_hotel/RegGayaHotel.txt", username + "," + password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_SUsername = new javax.swing.JTextField();
        txt_SPassword = new javax.swing.JPasswordField();
        btn_Register = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        GAYA_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 60, 60));

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/reenter-password.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 60, 60));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel2.setText("SIGN-UP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 570, -1));

        txt_SUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txt_SUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 320, 40));

        txt_SPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txt_SPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 320, 40));

        btn_Register.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/add-user.png"))); // NOI18N
        btn_Register.setText("REGISTER");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 160, 50));

        btn_Reset.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/rewind-button.png"))); // NOI18N
        btn_Reset.setText("RESET");
        btn_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ResetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 160, 50));

        btn_Back.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/left-arrow-in-circular-button-black-symbol.png"))); // NOI18N
        btn_Back.setText("BACK");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 150, 50));

        GAYA_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking_hotel/Images/gaya.jpg"))); // NOI18N
        getContentPane().add(GAYA_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ResetMouseClicked
        // TODO add your handling code here:
        txt_SUsername.setText("");
        txt_SPassword.setText("");
        txt_SUsername.grabFocus();
    }//GEN-LAST:event_btn_ResetMouseClicked

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        Login_Hotel login = new Login_Hotel();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        String username = txt_SUsername.getText();
        String password = new String(txt_SPassword.getPassword());


        if (register(username, password)) {
            JOptionPane.showMessageDialog(this, "Registered successfully!!");
            Login_Hotel login = new Login_Hotel();
            login.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error occurred while registering user.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GAYA_BG;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txt_SPassword;
    private javax.swing.JTextField txt_SUsername;
    // End of variables declaration//GEN-END:variables
}
